/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Libro;
import controladores.ControladorBiblioteca;
import controladores.ControladorPrincipal;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author diego
 */
public class CRUDLibro extends javax.swing.JPanel {
    private ControladorPrincipal controladorPrincipal;
    private javax.swing.JPanel subPanelPrincipal;
    /**
     * Creates new form CRUDLibro
     */
    public CRUDLibro(ControladorPrincipal controladorPrincipal,javax.swing.JPanel subPanelPrincipal ) {
        this.controladorPrincipal = controladorPrincipal;
        this.subPanelPrincipal = subPanelPrincipal;
        initComponents();
        this.cargarTablaLibro(jTable1, this.controladorPrincipal.getControladorLibro().getLibros());
    }
    public  void limpiar_tabla(javax.swing.JTable  tabla) 
    {
        int filas = tabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    } 
   

    public void cargarTablaLibro(JTable tabla, ArrayList lista){
        limpiar_tabla(tabla);
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();   
        JTableHeader th; 
        th = tabla.getTableHeader(); 
        Font fuente = new Font("Tahoma", Font.BOLD, 12); 
        th.setForeground(java.awt.Color.BLACK);
        th.setBackground(java.awt.Color.white);
        th.setFont(fuente);    

        Libro aux = null;
        Iterator iter = lista.iterator();
        while (iter.hasNext()){
            aux = (Libro)iter.next();
            Object [] fila = new Object[6];
            fila[0] = aux.getIdentificador();
            fila[1] = aux.getNombre();
            fila[2] = aux.getISBN();
            fila[3] = aux.getAño();
            fila[4] = aux.getUnEditorial().getNombre();
            fila[5] = aux.getUnAutor().getNombre();
            modelo.addRow(fila);
        }
        modelo.rowsRemoved(null);    
        tabla.setModel(modelo);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_opcionesHabitacion = new javax.swing.JButton();
        btn_opcionesPileta = new javax.swing.JButton();
        btn_opcionesSalon = new javax.swing.JButton();
        btn_opcionesSalon1 = new javax.swing.JButton();
        pnll_Cuerpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel1.setLayout(new java.awt.GridLayout(6, 1));

        btn_opcionesHabitacion.setText("<html><p>Nuevo</p></html>");
        btn_opcionesHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesHabitacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_opcionesHabitacion);

        btn_opcionesPileta.setText("<html><p>Modificar</p></html>");
        btn_opcionesPileta.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesPileta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesPiletaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_opcionesPileta);

        btn_opcionesSalon.setText("Eliminar");
        btn_opcionesSalon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesSalonActionPerformed(evt);
            }
        });
        jPanel1.add(btn_opcionesSalon);

        btn_opcionesSalon1.setText("Ejemplares");
        btn_opcionesSalon1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesSalon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesSalon1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_opcionesSalon1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 109, 401));

        pnll_Cuerpo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnll_Cuerpo.setLayout(new javax.swing.BoxLayout(pnll_Cuerpo, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre ", "ISBN", "Año", "Editorial", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pnll_Cuerpo.add(jScrollPane1);

        add(pnll_Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 0, 485, 401));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opcionesHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesHabitacionActionPerformed
        FormLibro formLibro = new FormLibro(controladorPrincipal, jTable1,pnll_Cuerpo, null, this.subPanelPrincipal);
        pnll_Cuerpo.removeAll();
        pnll_Cuerpo.add(formLibro);
        pnll_Cuerpo.updateUI();
    }//GEN-LAST:event_btn_opcionesHabitacionActionPerformed

    private void btn_opcionesPiletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesPiletaActionPerformed
        //        Parametros_Pileta losParametros = new Parametros_Pileta(unaHosteria.getPileta());
        if(this.jTable1.getSelectedRow()!=-1)
        {
            int fila = this.jTable1.getSelectedRow();
            Integer unLibroSeleccionado = (Integer) this.jTable1.getValueAt(fila, 0);
           
            FormLibro empleadoLibro = new FormLibro(controladorPrincipal, jTable1,pnll_Cuerpo, unLibroSeleccionado, this.subPanelPrincipal);
            pnll_Cuerpo.removeAll();
            pnll_Cuerpo.add(empleadoLibro);
            pnll_Cuerpo.updateUI();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No ha seleccionado un Libro"," ",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_opcionesPiletaActionPerformed

    private void btn_opcionesSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesSalonActionPerformed
        //      Parametros_Salon parSal = new Parametros_Salon(unaHosteria);
    }//GEN-LAST:event_btn_opcionesSalonActionPerformed

    private void btn_opcionesSalon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesSalon1ActionPerformed
        // TODO add your handling code here:
        if(this.jTable1.getSelectedRow()!=-1)
        {
            int fila = this.jTable1.getSelectedRow();
            Integer unLibroSeleccionado = (Integer) this.jTable1.getValueAt(fila, 0);
            Libro unLibro = this.controladorPrincipal.getControladorLibro().buscarLibro(unLibroSeleccionado);
            CRUDEjemplar ejemplar = new CRUDEjemplar(unLibro, this.subPanelPrincipal);
            this.subPanelPrincipal.removeAll();
            this.subPanelPrincipal.add(ejemplar);
            this.subPanelPrincipal.updateUI();
        }
    }//GEN-LAST:event_btn_opcionesSalon1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_opcionesHabitacion;
    private javax.swing.JButton btn_opcionesPileta;
    private javax.swing.JButton btn_opcionesSalon;
    private javax.swing.JButton btn_opcionesSalon1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnll_Cuerpo;
    // End of variables declaration//GEN-END:variables
}
