/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Ejemplar;
import clases.Empleado;
import clases.Libro;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author diego
 */
public class CRUDEjemplar extends javax.swing.JPanel {
    private Libro unLibro;
    private javax.swing.JPanel subPanelPrincipal;
    /**
     * Creates new form CRUDEjemplar
     */
    public CRUDEjemplar(Libro unLibro, javax.swing.JPanel subPanelPrincipal) {
        this.unLibro =unLibro;
        this.subPanelPrincipal = subPanelPrincipal;
        initComponents();
        this.cargarTablaEjemplar(jTable1, unLibro.getEjemplares());
    }
    public  void limpiar_tabla(javax.swing.JTable  tabla) 
    {
        int filas = tabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    } 
   

    public void cargarTablaEjemplar(JTable tabla, ArrayList lista){
        limpiar_tabla(tabla);
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();   
        JTableHeader th; 
        th = tabla.getTableHeader(); 
        Font fuente = new Font("Tahoma", Font.BOLD, 12); 
        th.setForeground(java.awt.Color.BLACK);
        th.setBackground(java.awt.Color.white);
        th.setFont(fuente);    

        Ejemplar aux = null;
        Iterator iter = lista.iterator();
        while (iter.hasNext()){
            aux = (Ejemplar)iter.next();
            Object [] fila = new Object[7];
            fila[0] = aux.getIdEjemplar();
            fila[1] = aux.getIdentificador();
            fila[2] = aux.getNombre();
            fila[3] = aux.getISBN();
            fila[4] = aux.getAño();
            fila[5] = aux.getUnEditorial().getNombre();
            fila[6] = aux.getUnAutor().getNombre();

            modelo.addRow(fila);
        }
        modelo.rowsRemoved(null);    
        tabla.setModel(modelo);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_opcionesHabitacion = new javax.swing.JButton();
        btn_opcionesPileta = new javax.swing.JButton();
        btn_opcionesSalon = new javax.swing.JButton();
        pnll_Cuerpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Ejemplares"));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel2.setLayout(new java.awt.GridLayout(6, 1));

        btn_opcionesHabitacion.setText("<html><p>Nuevo</p></html>");
        btn_opcionesHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesHabitacionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_opcionesHabitacion);

        btn_opcionesPileta.setText("<html><p>Modificar</p></html>");
        btn_opcionesPileta.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesPileta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesPiletaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_opcionesPileta);

        btn_opcionesSalon.setText("Eliminar");
        btn_opcionesSalon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesSalonActionPerformed(evt);
            }
        });
        jPanel2.add(btn_opcionesSalon);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 109, 401));

        pnll_Cuerpo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnll_Cuerpo.setLayout(new javax.swing.BoxLayout(pnll_Cuerpo, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IDEjemplar", "IDLibro", "Nombre ", "ISBN", "Año", "Editorial", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pnll_Cuerpo.add(jScrollPane1);

        jPanel1.add(pnll_Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 0, 485, 401));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opcionesHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesHabitacionActionPerformed

    }//GEN-LAST:event_btn_opcionesHabitacionActionPerformed

    private void btn_opcionesPiletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesPiletaActionPerformed
        //        Parametros_Pileta losParametros = new Parametros_Pileta(unaHosteria.getPileta());
        if(this.jTable1.getSelectedRow()!=-1)
        {

        }
        else
        {
            JOptionPane.showMessageDialog(null,"No ha seleccionado un Ejemplar"," ",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_opcionesPiletaActionPerformed

    private void btn_opcionesSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesSalonActionPerformed
        //      Parametros_Salon parSal = new Parametros_Salon(unaHosteria);
    }//GEN-LAST:event_btn_opcionesSalonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_opcionesHabitacion;
    private javax.swing.JButton btn_opcionesPileta;
    private javax.swing.JButton btn_opcionesSalon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnll_Cuerpo;
    // End of variables declaration//GEN-END:variables
}
