/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorPrincipal;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author diego
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    private ControladorPrincipal controladorPrincipal;
    public VistaPrincipal(ControladorPrincipal controladorPrincipal) {
        this.controladorPrincipal = controladorPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        BTN_Diario = new javax.swing.JButton();
        BTN_Diario1 = new javax.swing.JButton();
        btnLibro = new javax.swing.JButton();
        btnLibro1 = new javax.swing.JButton();
        btnLibro2 = new javax.swing.JButton();
        btnLibro3 = new javax.swing.JButton();
        btnLibro4 = new javax.swing.JButton();
        pnl_Cuerpo = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Gestión de Biblioteca");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BTN_Diario.setFont(new java.awt.Font("Droid Sans", 0, 10)); // NOI18N
        BTN_Diario.setText("Lectores");
        BTN_Diario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_Diario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BTN_Diario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_Diario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DiarioActionPerformed(evt);
            }
        });

        BTN_Diario1.setFont(new java.awt.Font("Droid Sans", 0, 10)); // NOI18N
        BTN_Diario1.setText("Empleados");
        BTN_Diario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_Diario1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BTN_Diario1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_Diario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Diario1ActionPerformed(evt);
            }
        });

        btnLibro.setFont(new java.awt.Font("Droid Sans", 0, 10)); // NOI18N
        btnLibro.setText("Libros");
        btnLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLibro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });

        btnLibro1.setFont(new java.awt.Font("Droid Sans", 0, 10)); // NOI18N
        btnLibro1.setText("Editoriales");
        btnLibro1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibro1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLibro1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro1ActionPerformed(evt);
            }
        });

        btnLibro2.setFont(new java.awt.Font("Droid Sans", 0, 10)); // NOI18N
        btnLibro2.setText("Autores");
        btnLibro2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibro2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLibro2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro2ActionPerformed(evt);
            }
        });

        btnLibro3.setFont(new java.awt.Font("Droid Sans", 0, 10)); // NOI18N
        btnLibro3.setText("Configuración");
        btnLibro3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibro3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLibro3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro3ActionPerformed(evt);
            }
        });

        btnLibro4.setFont(new java.awt.Font("Droid Sans", 0, 10)); // NOI18N
        btnLibro4.setText("Permisos");
        btnLibro4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibro4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLibro4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLibro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(BTN_Diario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Diario1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_Diario1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(BTN_Diario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_Cuerpo.setBackground(new java.awt.Color(51, 51, 51));
        pnl_Cuerpo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnl_Cuerpo.setLayout(new javax.swing.BoxLayout(pnl_Cuerpo, javax.swing.BoxLayout.LINE_AXIS));

        panelCurves1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        pnl_Cuerpo.add(panelCurves1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(pnl_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_DiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DiarioActionPerformed
        CRUDLector lector = new CRUDLector(this.controladorPrincipal);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(lector);
        pnl_Cuerpo.updateUI();
    }//GEN-LAST:event_BTN_DiarioActionPerformed

    private void BTN_Diario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Diario1ActionPerformed
                                          
        CRUDEmpleado empleado = new CRUDEmpleado(this.controladorPrincipal);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(empleado);
        pnl_Cuerpo.updateUI();
    }//GEN-LAST:event_BTN_Diario1ActionPerformed

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        // TODO add your handling code here:
        CRUDLibro libro = new CRUDLibro(this.controladorPrincipal, this.pnl_Cuerpo);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(libro);
        pnl_Cuerpo.updateUI();
    }//GEN-LAST:event_btnLibroActionPerformed

    private void btnLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro1ActionPerformed
        // TODO add your handling code here:
        CRUDEditorial editorial = new CRUDEditorial(this.controladorPrincipal, this.pnl_Cuerpo);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(editorial);
        pnl_Cuerpo.updateUI();       
    }//GEN-LAST:event_btnLibro1ActionPerformed

    private void btnLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro2ActionPerformed
        // TODO add your handling code here:
        CRUDAutor autor = new CRUDAutor(this.controladorPrincipal, this.pnl_Cuerpo);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(autor);
        pnl_Cuerpo.updateUI();   
    }//GEN-LAST:event_btnLibro2ActionPerformed

    private void btnLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibro3ActionPerformed

    private void btnLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibro4ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Diario;
    private javax.swing.JButton BTN_Diario1;
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnLibro1;
    private javax.swing.JButton btnLibro2;
    private javax.swing.JButton btnLibro3;
    private javax.swing.JButton btnLibro4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private javax.swing.JPanel pnl_Cuerpo;
    // End of variables declaration//GEN-END:variables
}
